# =============================================================================
# services/database_service.py - SQL Server Database Service
# =============================================================================
# This file manages the connection and query execution against SQL Server:
#   - Establishes a connection to SQL Server using pyodbc and the
#     credentials from config/environment variables.
#   - Executes the SQL query generated by the LLM against the database.
#   - Fetches and formats the query results (column names + rows) into
#     a structured response for the frontend.
#   - Handles connection pooling, timeouts, and error handling for
#     invalid SQL, permission errors, or connection failures.
#   - Provides a function to test the database connection on startup.
# =============================================================================
